version: '3.1'
services:
  app:
    container_name: springboot-hotel
    image: springboot-hotel
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=root
      - POSTGRES_DB=hoteldb